[build]
  # Commande de build
  command = "npm run build:netlify"
  # Dossier de sortie (Angular SSR)
  publish = "dist/label-conseil/browser"
  # Dossier des fonctions Netlify (pour l'API)
  functions = "netlify/functions"

[build.environment]
  # Variables d'environnement pour le build
  NODE_VERSION = "20"

# Configuration du serveur SSR
[[redirects]]
  # Redirection de la racine vers le serveur SSR
  from = "/*"
  to = "/.netlify/functions/ssr"
  status = 200
  force = true

# Redirection des erreurs 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Headers de sécurité et performance
[[headers]]
  for = "/*"
  [headers.values]
    # Sécurité
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance et cache
    Cache-Control = "public, max-age=31536000, immutable"
    
    # CORS pour les ressources statiques
    Access-Control-Allow-Origin = "*"

# Headers spécifiques pour les assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Headers pour les images
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.webp"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers pour les polices
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "*.woff"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Access-Control-Allow-Origin = "*"

# Headers pour les fichiers CSS et JS
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Configuration des fonctions Netlify
[functions]
  # Dossier des fonctions
  directory = "netlify/functions"
  # Node.js version pour les fonctions
  node_bundler = "esbuild"

# Configuration des Edge Functions (plus performantes)
[edge_functions]
  directory = "netlify/edge-functions"

# Configuration du serveur SSR
[functions."ssr"]
  # Fichier principal de la fonction SSR
  included_files = ["dist/label-conseil/browser/**/*"]

# Configuration des plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"

# Configuration des formulaires (si vous en avez)
[forms]
  [forms."contact-form"]
    name = "Formulaire de contact"
    action = "/success"
    method = "POST"

# Configuration des notifications
[notifications]
  # Slack (optionnel)
  # [notifications.slack]
  #   channel = "#deployments"
  #   webhook_url = "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"

# Configuration de l'optimisation des images
[images]
  # Compression automatique des images
  compress = true
  # Formats modernes
  formats = ["webp", "avif"]

# Configuration de la compression
[build.processing]
  # Compression des assets
  css = { bundle = true, minify = true }
  js = { bundle = true, minify = true }
  html = { pretty_urls = true }
  images = { compress = true }

# Configuration des variables d'environnement de production
[context.production.environment]
  NODE_ENV = "production"
  ANGULAR_ENV = "production"

# Configuration des variables d'environnement de preview
[context.deploy-preview.environment]
  NODE_ENV = "staging"
  ANGULAR_ENV = "staging"

# Configuration des variables d'environnement de développement
[context.deploy-preview.environment]
  NODE_ENV = "development"
  ANGULAR_ENV = "development"
